update 0.0.7

diff --git a/entry b/entry
--- a/entry
+++ b/entry
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
 set -o errexit
 set -o nounset
@@ -6,114 +6,30 @@ set -o pipefail
 
 cleanup() {
     echo "cleaning up..."
-    kill TERM "$openvpn_pid"
-    if [[ -n "$EXIT_SHELL" ]]; then
-      echo "exec exit shell: $EXIT_SHELL"
-      bash -c "$EXIT_SHELL"
-    fi
+    kill -9 "$openvpn_pid"
     exit 0
 }
 
-# 执行配置脚本，在启动前执行
-if [[ -n $CONF_SHELL ]]; then
-    echo "exec conf shell: $CONF_SHELL"
-    bash -c "$CONF_SHELL"
-fi
-
-# OpenVPN OPVPN_AUTH include ":", is user:pass, wirte to file
-if [[ $OPVPN_AUTH == *:* ]]; then
-    echo "$OPVPN_AUTH" | tr ':' '\n' > /vpn/auth.txt
-    OPVPN_AUTH=/vpn/auth.txt
-fi
-# OpenVPN auth file.
-if [[ ! -f $OPVPN_AUTH ]]; then
-    echo "openvpn auth file not found: $OPVPN_AUTH"
-    exit 1
-fi
-
-# if file is prefix http, download it.
-if [[ $OPVPN_CONF == http* ]]; then
-    echo "downloading openvpn conf file: $OPVPN_CONF"
-    curl -ksSL "$OPVPN_CONF" -o /vpn/openvpn.conf
-    OPVPN_CONF=/vpn/openvpn.conf
-fi
-# OpenVPN configuration file.
-if [[ ! -f $OPVPN_CONF ]]; then
-    echo "openvpn conf file not found: $OPVPN_CONF"
-    exit 1
-fi
-
-# if file is prefix http, download it.
-if [[ $DANTE_CONF == http* ]]; then
-    echo "downloading dante conf file: $DANTE_CONF"
-    curl -ksSL "$DANTE_CONF" -o /vpn/sockd.conf
-    DANTE_CONF=/vpn/sockd.conf
-fi
-# Dante configuration file.
-if [[ ! -f $DANTE_CONF ]]; then
-    # default dante conf file.
-    DANTE_CONF=/vpn/sockd.default.conf
-fi
-
-# 处理OPSKIP_IPS
-if [[ -n "$OPSKIP_IPS" ]]; then
-    echo "using openvpn allows ips: $OPSKIP_IPS"
-    echo "$OPSKIP_IPS" | tr ',' '\n' | while read -r line; do
-        if [[ $line == */* ]]; then
-            # ip/mask => ip mask
-            ip=${line%/*}
-            mk=${line#*/}
-            mk0=$(( (1 << (32 - $mk)) - 1 ))
-            mk1=$((mk0 >> 24 & 0xff ^ 0xff))
-            mk2=$((mk0 >> 16 & 0xff ^ 0xff))
-            mk3=$((mk0 >> 8  & 0xff ^ 0xff))
-            mk4=$((mk0 & 0xff ^ 0xff))
-            line="$ip $mk1.$mk2.$mk3.$mk4"
-        fi
-        echo "route $line net_gateway" >> "$OPVPN_CONF"
-    done
-fi
-
 # 打印启动使用的配置
-echo "using openvpn conf file: $OPVPN_CONF"
-echo "using openvpn auth file: $OPVPN_AUTH"
-
-mkdir /vpn/log
+echo "using openvpn conf file: $OV_CONF_PATH"
+echo "using openvpn auth file: $OV_USER_PASS"
 
 # OpenVPN Running.
-openvpn --config "$OPVPN_CONF" "--auth-user-pass" "$OPVPN_AUTH" &
-# OpenVPN PID.
+mkdir /vpn/log
+openvpn --config "$OV_CONF_PATH" "--auth-user-pass" "$OV_USER_PASS" &
 openvpn_pid=$!
+
+# 显示连接状况
+while [[ ! -e /sys/class/net/tun0 ]]; do
+    sleep 2 # 等待tun0出现，如果没有出现，说明openvpn启动失败
+    if ! kill -0 "$openvpn_pid" 2>/dev/null; then
+        echo "openvpn process not found, openvpn start failed."
+        exit 1
+    fi
+done
+echo "" && echo "tun0 is installed"
 
 trap cleanup TERM
 
-# Dante Running. -D: run as daemon
-# sockd -f "$DANTE_CONF" -D
-if [[ "$SOCKS5" == "on" ]]; then
-    echo "using dante conf file: $DANTE_CONF"
-    sleep 5 # 延迟10s启动dante代理,openvpn启动tun0慢一些
-    sockd -f "$DANTE_CONF" -D
-fi
+wait $openvpn_pid
 
-# wait $openvpn_pid
-
-#=========================================================
-# 成功启动后执行的脚本
-if [[ -n "$SUCC_SHELL" ]]; then
-  echo "exec succ shell: $SUCC_SHELL"
-  bash -c "$SUCC_SHELL"
-fi
-if [[ -n "$TESTIP_URI" ]]; then
-    sleep 5
-    echo "public ip: $(curl -ksSL $TESTIP_URI)"
-fi
-# 如果存在健康检查地址，就进行健康检查，否则等待openvpn进程结束
-if [[ -n "$HEALTH_SHELL" ]]; then
-    # 如果$openvpn_pid进程存在，就执行健康检查脚本
-    while ! kill -0 "$openvpn_pid" >/dev/null; do
-        sleep 5
-        bash -c "$HEALTH_SHELL" # 不忽略异常，异常会触发重启
-    done
-else
-    wait $openvpn_pid
-fi
